Changed call .distinct() because it caused a bug.
Changed the call .distinct('word_id') to .distinct() in
tests/test_importers.py because calling it with a parameter
was supported by another version of postgresql but it wasn't
by this version of postgresql or MySQL.

With this change the error does not happen and the test
runs correctly and all tests checks result in an 'OK'

(There were 4 error but I only write the first because all
the errors happen because of the same reason and the tracebacks
are quite similar)

======================================================================
ERROR: test_import (tests.test_importers.ImportVariationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/alejandro/backend_git/tests/test_importers.py", line 197, in test_import
    self.assertEqual(self.NUMBER_OF_ENTRIES, qs.count())
  File "/home/alejandro/backend_proj_env/lib/python3.8/site-packages/django/db/models/query.py", line 392, in count
    return self.query.get_count(using=self.db)
  File "/home/alejandro/backend_proj_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 504, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/home/alejandro/backend_proj_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 472, in get_aggregation
    outer_query.add_subquery(inner_query, using)
  File "/home/alejandro/backend_proj_env/lib/python3.8/site-packages/django/db/models/sql/subqueries.py", line 194, in add_subquery
    self.subquery, self.sub_params = query.get_compiler(using).as_sql(with_col_aliases=True)
  File "/home/alejandro/backend_proj_env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 495, in as_sql
    distinct_result, distinct_params = self.connection.ops.distinct_sql(
  File "/home/alejandro/backend_proj_env/lib/python3.8/site-packages/django/db/backends/base/operations.py", line 172, in distinct_sql
    raise NotSupportedError('DISTINCT ON fields is not supported by this database backend')
django.db.utils.NotSupportedError: DISTINCT ON fields is not supported by this database backend